#ifndef EVENTENUM_HH
#define EVENTENUM_HH

enum class EventEnum {
    SUCCESS,
    INVALID_COMMAND,
    INVALID_FILE_PATH,
    SYNTAX_ERROR,
    UNDEFINED_SYMBOL,
    FILE_FORMAT_ERROR,
    ERROR_DETECTED,
    FILE_ERROR,
    FILE_NOT_FOUND,
    OTHER_ERROR
};

#endif
